LTO_ENABLE = yes            # Enables Link Time Optimization
COMBO_ENABLE = yes          # Enables combos
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = no        # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
RGBLIGHT_ENABLE = yes       # Enable underlight
SPLIT_KEYBOARD = yes
OLED_ENABLE = yes